"""
مولد المكتبات المخصصة
"""

import os
import re
from pathlib import Path
from typing import Dict, Any, List, Optional
import shutil
import subprocess
import tempfile
import json

class Bundler:
    """فئة إنشاء الحزم المخصصة"""
    
    def __init__(self, analysis: Dict[str, Any], project_path: str):
        self.analysis = analysis
        self.project_path = Path(project_path)
        self.output_dir = self.project_path / 'bundles'
        self.output_dir.mkdir(exist_ok=True)
        
        # قوالب المكتبات
        self.library_templates = {
            'lodash': self._create_lodash_bundle,
            'jquery': self._create_jquery_bundle,
            'axios': self._create_axios_bundle,
            'moment': self._create_moment_bundle,
            'react': self._create_react_bundle,
            'vue': self._create_vue_bundle
        }
    
    def create_bundles(self) -> Dict[str, str]:
        """إنشاء حزم مخصصة لجميع المكتبات المكتشفة"""
        bundles = {}
        
        for lib_name, lib_data in self.analysis['libraries'].items():
            print(f"📦 إنشاء حزمة مخصصة لـ {lib_name}...")
            
            # استخدام قالب مخصص إذا كان متوفراً
            if lib_name in self.library_templates:
                bundle_path = self.library_templates[lib_name](lib_name, lib_data)
            else:
                # قالب عام
                bundle_path = self._create_generic_bundle(lib_name, lib_data)
            
            if bundle_path:
                bundles[lib_name] = bundle_path
                print(f"✅ تم إنشاء: {bundle_path}")
        
        return bundles
    
    def _create_lodash_bundle(self, lib_name: str, lib_data: Dict) -> Optional[str]:
        """إنشاء حزمة مخصصة لـ lodash"""
        functions_used = set()
        
        # استخراج أسماء الدوال المستخدمة
        for func_usage in lib_data['functions_used']:
            match = re.match(r'lodash\.(\w+)', func_usage)
            if match:
                functions_used.add(match.group(1))
        
        if not functions_used:
            return None
        
        # إنشاء المحتوى
        content = """// Custom Lodash Bundle
// Generated by JS Custom Bundler
// Used functions: {functions}

(function(global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
    typeof define === 'function' && define.amd ? define(['exports'], factory) :
    (global = typeof globalThis !== 'undefined' ? globalThis : global || self, factory(global._ = {}));
}(this, (function(exports) {{
    'use strict';

{functions_code}
    
    exports.__esModule = true;
}})));
""".format(
            functions=', '.join(sorted(functions_used)),
            functions_code=self._generate_lodash_functions(functions_used)
        )
        
        # حفظ الحزمة
        return self._save_bundle(lib_name, content)
    
    def _generate_lodash_functions(self, functions: set) -> str:
        """توليد كود الدوال المستخدمة من lodash"""
        # هذا مثال مبسط، في الواقع يجب استيراد الدوال الفعلية
        functions_code = []
        for func in sorted(functions):
            functions_code.append(f"""
    function {func}(value) {{
        // Placeholder for lodash.{func}
        console.log('lodash.{func} called with:', value);
        return value;
    }}
    
    exports.{func} = {func};""")
        
        return '\n'.join(functions_code)
    
    def _create_jquery_bundle(self, lib_name: str, lib_data: Dict) -> Optional[str]:
        """إنشاء حزمة مخصصة لـ jQuery"""
        content = """// Custom jQuery Bundle
// Generated by JS Custom Bundler

(function(global, factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        module.exports = global.document ?
            factory(global, true) :
            function(w) {
                if (!w.document) {
                    throw new Error("jQuery requires a window with a document");
                }
                return factory(w);
            };
    } else {
        factory(global);
    }
}(typeof window !== "undefined" ? window : this, function(window, noGlobal) {
    
    var jQuery = function(selector, context) {
        return new jQuery.fn.init(selector, context);
    };
    
    // Basic jQuery functionality
    jQuery.fn = jQuery.prototype = {
        init: function(selector, context) {
            // Simplified implementation
            if (!selector) {
                return this;
            }
            return this;
        },
        
        ready: function(fn) {
            document.addEventListener('DOMContentLoaded', fn);
            return this;
        },
        
        css: function(properties) {
            // Simplified CSS method
            return this;
        },
        
        on: function(event, handler) {
            // Simplified event handler
            return this;
        }
    };
    
    jQuery.fn.init.prototype = jQuery.fn;
    
    // Global $
    if (!noGlobal) {
        window.jQuery = window.$ = jQuery;
    }
    
    return jQuery;
}));
"""
        return self._save_bundle(lib_name, content)
    
    def _create_axios_bundle(self, lib_name: str, lib_data: Dict) -> Optional[str]:
        """إنشاء حزمة مخصصة لـ axios"""
        content = """// Custom Axios Bundle
// Generated by JS Custom Bundler

const axios = (function() {
    'use strict';
    
    function createInstance() {
        const instance = function axios(config) {
            return instance.request(config);
        };
        
        instance.request = function(config) {
            return new Promise((resolve, reject) => {
                const xhr = new XMLHttpRequest();
                const url = config.baseURL ? config.baseURL + config.url : config.url;
                
                xhr.open(config.method || 'get', url);
                
                // Set headers
                if (config.headers) {
                    Object.keys(config.headers).forEach(key => {
                        xhr.setRequestHeader(key, config.headers[key]);
                    });
                }
                
                xhr.onload = function() {
                    const response = {
                        data: JSON.parse(xhr.responseText),
                        status: xhr.status,
                        statusText: xhr.statusText,
                        headers: xhr.getAllResponseHeaders(),
                        config: config,
                        request: xhr
                    };
                    resolve(response);
                };
                
                xhr.onerror = function() {
                    reject(new Error('Network Error'));
                };
                
                xhr.send(config.data);
            });
        };
        
        // HTTP methods
        ['get', 'delete', 'head', 'options'].forEach(method => {
            instance[method] = function(url, config) {
                return instance.request({ ...config, method, url });
            };
        });
        
        ['post', 'put', 'patch'].forEach(method => {
            instance[method] = function(url, data, config) {
                return instance.request({ ...config, method, url, data });
            };
        });
        
        return instance;
    }
    
    const axios = createInstance();
    
    // Create method
    axios.create = function(config) {
        return createInstance(config);
    };
    
    return axios;
})();

// Export for different environments
if (typeof module !== 'undefined' && module.exports) {
    module.exports = axios;
} else if (typeof define === 'function' && define.amd) {
    define([], function() { return axios; });
} else {
    window.axios = axios;
}
"""
        return self._save_bundle(lib_name, content)
    
    def _create_moment_bundle(self, lib_name: str, lib_data: Dict) -> Optional[str]:
        """إنشاء حزمة مخصصة لـ moment"""
        content = """// Custom Moment Bundle
// Generated by JS Custom Bundler

(function(global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
    typeof define === 'function' && define.amd ? define(factory) :
    global.moment = factory();
}(this, (function() {
    'use strict';
    
    var moment = function(dateString, format) {
        return new MomentWrapper(dateString, format);
    };
    
    function MomentWrapper(dateString, format) {
        this._date = dateString ? new Date(dateString) : new Date();
    }
    
    MomentWrapper.prototype = {
        format: function(formatString) {
            var date = this._date;
            return formatString
                .replace('YYYY', date.getFullYear())
                .replace('MM', String(date.getMonth() + 1).padStart(2, '0'))
                .replace('DD', String(date.getDate()).padStart(2, '0'))
                .replace('HH', String(date.getHours()).padStart(2, '0'))
                .replace('mm', String(date.getMinutes()).padStart(2, '0'))
                .replace('ss', String(date.getSeconds()).padStart(2, '0'));
        },
        
        fromNow: function() {
            var now = new Date();
            var diff = now - this._date;
            var seconds = Math.floor(diff / 1000);
            
            if (seconds < 60) return 'a few seconds ago';
            if (seconds < 3600) return Math.floor(seconds / 60) + ' minutes ago';
            if (seconds < 86400) return Math.floor(seconds / 3600) + ' hours ago';
            return Math.floor(seconds / 86400) + ' days ago';
        },
        
        add: function(amount, unit) {
            var date = new Date(this._date.getTime());
            
            switch(unit) {
                case 'days': date.setDate(date.getDate() + amount); break;
                case 'months': date.setMonth(date.getMonth() + amount); break;
                case 'years': date.setFullYear(date.getFullYear() + amount); break;
            }
            
            return new MomentWrapper(date);
        }
    };
    
    // Static methods
    moment.locale = function() { return 'en'; };
    moment.utc = function(dateString) {
        return new MomentWrapper(dateString ? dateString + 'Z' : undefined);
    };
    
    return moment;
})));
"""
        return self._save_bundle(lib_name, content)
    
    def _create_react_bundle(self, lib_name: str, lib_data: Dict) -> Optional[str]:
        """إنشاء حزمة مخصصة لـ React (مبسط)"""
        content = """// Custom React Bundle (Simplified)
// Generated by JS Custom Bundler

const React = (function() {
    'use strict';
    
    function createElement(type, props, ...children) {
        return {
            $$typeof: Symbol.for('react.element'),
            type: type,
            props: {
                ...props,
                children: children.length === 1 ? children[0] : children
            }
        };
    }
    
    function useState(initialValue) {
        let state = initialValue;
        
        function setState(newValue) {
            state = newValue;
            // In real React, this would trigger re-render
        }
        
        return [state, setState];
    }
    
    function useEffect(effect, deps) {
        // Simplified effect
        effect();
    }
    
    return {
        createElement,
        useState,
        useEffect,
        Fragment: Symbol.for('react.fragment')
    };
})();

// Export
if (typeof module !== 'undefined' && module.exports) {
    module.exports = React;
} else {
    window.React = React;
}
"""
        return self._save_bundle(lib_name, content)
    
    def _create_vue_bundle(self, lib_name: str, lib_data: Dict) -> Optional[str]:
        """إنشاء حزمة مخصصة لـ Vue (مبسط)"""
        content = """// Custom Vue Bundle (Simplified)
// Generated by JS Custom Bundler

const Vue = (function() {
    'use strict';
    
    function createApp(component) {
        return {
            mount(selector) {
                const el = document.querySelector(selector);
                if (el && component.render) {
                    el.innerHTML = component.render();
                }
                return this;
            }
        };
    }
    
    function reactive(data) {
        return new Proxy(data, {
            get(target, key) {
                return target[key];
            },
            set(target, key, value) {
                target[key] = value;
                // In real Vue, this would trigger reactivity
                return true;
            }
        });
    }
    
    function ref(value) {
        return { value };
    }
    
    return {
        createApp,
        reactive,
        ref
    };
})();

// Export
if (typeof module !== 'undefined' && module.exports) {
    module.exports = Vue;
} else {
    window.Vue = Vue;
}
"""
        return self._save_bundle(lib_name, content)
    
    def _create_generic_bundle(self, lib_name: str, lib_data: Dict) -> Optional[str]:
        """إنشاء حزمة عامة للمكتبات غير المعروفة"""
        content = f"""// Custom Bundle for {lib_name}
// Generated by JS Custom Bundler
// This is a placeholder bundle

console.log('{lib_name} custom bundle loaded');

// Placeholder module
const {lib_name.replace('-', '_')} = {{
    version: '1.0.0-custom',
    description: 'Custom bundle generated by JS Custom Bundler'
}};

// Export based on environment
if (typeof module !== 'undefined' && module.exports) {{
    module.exports = {lib_name.replace('-', '_')};
}} else if (typeof define === 'function' && define.amd) {{
    define([], function() {{ return {lib_name.replace('-', '_')}; }});
}} else {{
    window.{lib_name.replace('-', '_')} = {lib_name.replace('-', '_')};
}}
"""
        return self._save_bundle(lib_name, content)
    
    def _save_bundle(self, lib_name: str, content: str) -> str:
        """حفظ الحزمة وإنشاء نسخة مضغوطة"""
        # حفظ الإصدار الكامل
        bundle_path = self.output_dir / f'{lib_name}.custom.js'
        with open(bundle_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        # إنشاء نسخة مضغوطة (مبسطة)
        minified = self._minify_js(content)
        min_path = self.output_dir / f'{lib_name}.custom.min.js'
        with open(min_path, 'w', encoding='utf-8') as f:
            f.write(minified)
        
        # إنشاء source map (مبسط)
        map_path = self.output_dir / f'{lib_name}.custom.min.js.map'
        with open(map_path, 'w', encoding='utf-8') as f:
            json.dump({
                "version": 3,
                "file": f"{lib_name}.custom.min.js",
                "sources": [f"{lib_name}.custom.js"],
                "mappings": ""
            }, f, indent=2)
        
        return str(bundle_path)
    
    def _minify_js(self, content: str) -> str:
        """ضغط كود JavaScript (تنفيذ مبسط)"""
        # إزالة التعليقات
        content = re.sub(r'//.*', '', content)
        content = re.sub(r'/\*.*?\*/', '', content, flags=re.DOTALL)
        
        # إزالة المسافات البيضاء الزائدة
        content = re.sub(r'\s+', ' ', content)
        content = re.sub(r'\s*([=+\-*/(){}\[\].,;:])\s*', r'\1', content)
        
        return content.strip()